name: 'openai'
version: '0.1.0'

config-version: 2
require-dbt-version: [">=1.3.0", "<3.0.0"]

models:
  openai:
    +schema: openai_reports
    +materialized: table
    staging:
      +schema: openai_staging
      +materialized: view
      tmp:
        +schema: openai_staging
        +materialized: view
    intermediate:
      +schema: openai_staging
      +materialized: ephemeral
